### ISSUE TITLE
[FEATURE] Branches for specific ckan versions.

### ISSUE THREAD

**Issue by Sameer25-py** [keitaroinc/ckanext-visualize#48]
**Is your feature request related to a problem? Please describe.**
I am using this extension for an open data portal. I have tested it on the dev instance in the past month and planned to deploy it on the production server this week. I clone the repo on the production server and now due to recent commits, its not working on the same CKAN version.

**Describe the solution you'd like**
If branches are added to the repo, it would be a lot of help because I really want to add this extension to the portal and now I am reverting and checking out all the commits to get to before the breaking commit happened.

**Additional context**
CKAN version 2.8.3 (link digital AMI).

**Comment by blazhovsky** [comment]
Hey @Sameer25-py! Thanks for reporting this.

You can use [this](https://github.com/keitaroinc/ckanext-visualize/tree/ckan-2.8) branch for CKAN 2.8 and below. Keep in mind we are currently migrating from Travis to GHA so some checks might not be passing.

**Comment by Sameer25-py** [comment]
Thank you so much. Also, just wanted to ask if there is any way to change the aggregation type from count.

**Comment by duskobogdanovski** [comment]
@Sameer25-py could you please create another issue with the appropriate description and you can create a pull request with the suggested changes so we can review? Thanks.
